[project]
name = "automated-research-report-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
]

[tool.uv.workspace]
members = [
    ".",
    ".",
]

[tool.uv.sources]
automated-research-report-generation = { workspace = true }

[dependency-groups]
dev = [
    "automated-research-report-generation",
    "langgraph>=0.6.8",
]
